<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net6.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <NoWarn>CS8032</NoWarn>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <ApplicationIcon>icon\icon.ico</ApplicationIcon>
    <AssemblyName>UnlockToPhoto</AssemblyName>
    <RootNamespace>UnlockToPhoto</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="icon\icon.ico">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="OpenCvSharp4" Version="4.13.0.20260627" />
    <PackageReference Include="OpenCvSharp4.runtime.win" Version="4.13.0.20260627" />
    <PackageReference Include="System.Management" Version="6.0.0" />
  </ItemGroup>

</Project>
